### ISSUE TITLE
Instant Desync on connect after 2 hours of multiplayer

### ISSUE THREAD

**Issue by skoapie** [thomaswp/BeaverBuddies#10] opened 2024-02-26 18:42 UTC
**Describe the bug**
* What happened: Desync,
* What were your doing right before this happened?: placing a bakery

**Logs**
only have my own (host)
[LogOutput-copy.log](https://github.com/thomaswp/BeaverBuddies/files/14409255/LogOutput-copy.log)

**To Reproduce**
1. Download [Multiplayer - Demelza (15).txt](https://github.com/thomaswp/BeaverBuddies/files/14409348/Multiplayer.-.Demelza.15.txt)
2.  rename the file "Multiplayer.-.Demelza.15.txt" to "Multiplayer - Demelza (15).timber"
3. Make a folder named 'Multiplayer - Demelza' in the saves folder of Timberborn and save the file there.
1. Play the savegame and let someone connect and wait a minute or click on 1x speed and after seconds or a minute u will get a desync, perhaps place a building down to trigger it.

**Screenshots**
Firstly, your mod is really cool man! Thanks for it! 
Through the playthrough we had some desync issues but not a huge problem until +- 2 hours in the game that we always desynced on connect, even thought we didn't do anything. i suspect for the beavers not being able to reach power shafts it caused an issue somehow. (in the save i had already deleted those)
![timberborn-shafts](https://github.com/thomaswp/BeaverBuddies/assets/17565375/fe82a1b4-0f1e-4b36-94ce-6366a6d04b24)

**Desktop (please complete the following information for **both** Host and Client):**
 - OS: Windows 10
 - Timberborn version: 0.5.9.1-33dabbc-sw i think (played yesterday)
 - BeaverBuddies version: current (downloaded yesterday)

**Comment by thomaswp** [comment] 2024-02-27 00:39
Thanks for working to make this reproducible! I'll take a look and see if I can confirm why things are desyncing. If you're right, it could be something pretty simple to fix.

**Comment by thomaswp** [comment] 2024-02-27 02:29
Ok, I was able to reproduce the issue, No immediate red flags, so it'll take me some time to diagnose. I did also get a crash related to beaver swimming animations that I'll try to reproduce - may be related, since I see some construction there? Not sure. It's possible it's the same as #7 and I'm just misunderstanding the cause. I'll keep you posted. Glad you've enjoyed it and sorry you're at a dead end right now :/

**Comment by skoapie** [comment] 2024-02-27 08:50
Interesting that the bug could be of of the beavers swimming, I had no clue.

Thank you for taking your free time to work on this man! Any way I could buy you a coffee?

**Comment by skoapie** [comment] 2024-02-27 12:40
Ps want me to make a port forwarding guide for windows specific to timberborn? Would probably be helpful for players who don’t know anything about tech

**Comment by thomaswp** [comment] 2024-02-28 02:01
A port forwarding guide would be a great way to say thank you. Maybe put it in a gist and I can add it to the wiki? I don't think they support PRs.

**Comment by skoapie** [comment] 2024-03-04 19:45
Ah yeah i did some research but the only thing specific to Timberborn would be the Windows Firewall part but Timberborn already has the ports opened, it really depends on which router you use what kind of guide you would use.

**Comment by skoapie** [comment] 2024-03-04 19:58
Here is the gist tho, don't know how usefull it would be:
https://gist.github.com/skoapie/829cae8aa7288633ddda275baf6a20e0

**Comment by skoapie** [comment] 2024-03-04 20:07
Here is the gist tho:
https://gist.github.com/skoapie/851e46e7bb961f57237327b5646762e4

**Comment by thomaswp** [comment] 2024-03-15 14:08
Thanks - added! Also, I know this conversation has gotten a bit sidetracked from your original issue. I'm still trying to isolate a fix. I've tried removing randomness, parallel ticking and other things and it's still happening, so I'm not sure what's going on.

**Comment by thomaswp** [comment] 2024-03-23 02:14
Hey! I think I may have found the source of your desync (or at least one of them). I'm testing it under a few conditions to see how robust it is, but hopefully will have a fix out this weekend! Fingers crossed it works out.

**Comment by skoapie** [comment] 2024-03-25 16:47
That's awesome man! I'm really curious as to what the problem was.

**Comment by thomaswp** [comment] 2024-03-26 02:23
Alright, the fix is live (though probably needs more testing). Could you try [v1.15-beta](https://mod.io/g/timberborn/m/beaverbuddies) and see if it fixes your issue. If not could you upload your save game here or to the discord so I can reproduce it?

For your curiosity... there were actually two issues that each independently caused the desync by making trees and other reproducing living things desync:
* The first was that the game getting a random index of a HasSet, and the index order of a HashSet isn't well defined, so I'm pretty sure that was causing some issues.
* The second and more important is that the game actually does some random stuff *while loading the save*, which I was not expecting. So before the Client can connect and sync up it's random seed, it set some tree's death timers, which we don't experience until much later in a save. Hopefully not the games will both start loading from a fixed seed (this should also help with reproducing errors - they should happen at the same time each time you load a game, I hope).

**Comment by skoapie** [comment] 2024-03-26 09:27
That second bug looks like a horror to debug, oh my.
Glad you found it, we will test it tonight and i'll let you know what the results are :)

**Comment by thomaswp** [comment] 2024-04-05 23:10
@skoapie have you encountered the bug again? I fixed on but I've realized there's a separate desync issue affecting another map I've tested on.

**Comment by thomaswp** [comment] 2024-05-20 02:38
Good news all - I think I've figured out a primary cause of the desyncs and have a fix in the works. I'll need some time to test and polish it, but it seems to work on the maps you sent.

**Comment by thomaswp** [comment] 2024-06-15 15:26
Hey, I've recently fixed a number of desync issues in v1.1.8, including the ones I observed in this tread. Please update BeaverBuddies, and if the problem persists, please upload your save file again so I can replicate it. I'm going to mark this as closed for now, but please reopen it the problem persists!

**Closed by thomaswp** 2024-06-15 15:26 UTC
Labels: desync

**Comment by skoapie** [comment] 2024-06-16 09:23
Hey thomas, amazing work! Sadly we dont play the game anymore so i cant test it
