### ISSUE TITLE
Few crashes detected while playing for a couple hours

### ISSUE THREAD

**Issue by joseprl89** [thomaswp/BeaverBuddies#15] opened 2024-04-01 07:36 UTC
**Important**: Do not restart Timberborn after your bug has happened. This will overwrite your log file, which is important for diagnosing bugs! You can close the game, but do not restart it until you have submitted this report.

**Describe the bug**
* What happened: Occasional crashes, we couldn't find a pattern to consistently reproduce. Looking at crash reports seems to be related to spawning entities and adding twice to a dictionary.
* What were your doing right before this happened?: nothing specific

**Logs**: On both the server and client computer, do the following steps:

[server.log](https://github.com/thomaswp/BeaverBuddies/files/14820866/server.log)

**To Reproduce**:

No steps to reproduce identified.

**Desktop (please complete the following information for **both** Host and Client):**
 - OS: Windows 11 server and Windows 10 for the client
 - Timberborn version: 0.5.9.1
 - BeaverBuddies version: 1.1.5-beta

Crash logs:

[error-report-2024-04-01-09h17m52s.zip](https://github.com/thomaswp/BeaverBuddies/files/14820881/error-report-2024-04-01-09h17m52s.zip)
[error-report-2024-04-01-09h28m29s.zip](https://github.com/thomaswp/BeaverBuddies/files/14820883/error-report-2024-04-01-09h28m29s.zip)
[error-report-2024-03-31-20h09m11s.zip](https://github.com/thomaswp/BeaverBuddies/files/14820884/error-report-2024-03-31-20h09m11s.zip)
[error-report-2024-03-31-20h22m26s.zip](https://github.com/thomaswp/BeaverBuddies/files/14820885/error-report-2024-03-31-20h22m26s.zip)
[error-report-2024-04-01-08h53m07s.zip](https://github.com/thomaswp/BeaverBuddies/files/14820886/error-report-2024-04-01-08h53m07s.zip)
[error-report-2024-04-01-09h12m51s.zip](https://github.com/thomaswp/BeaverBuddies/files/14820887/error-report-2024-04-01-09h12m51s.zip)

**Comment by thomaswp** [comment] 2024-04-05 00:53
Thanks - looks like this is a duplicate of #16 so I'll keep you up to date there, but the additional logs help.

**Comment by joseprl89** [comment] 2024-04-05 07:07
Will watch that issue then, feel free to close this one!

**Comment by thomaswp** [comment] 2024-04-05 18:13
Thanks - left some questions for you there.

**Closed by thomaswp** 2024-04-05 18:13 UTC
